### PR TITLE
Fix data attribute bug

### PR DESCRIPTION
**Pull request by jvanbruegge**
See https://github.com/cyclejs-community/create-cycle-app-flavors/issues/36

### CODE REVIEW

**Comment by jvanbruegge** [comment]
tested locally, has the desired effect

**Comment by Swizz** [comment]
The #7 issue, wasnt true regarding the way Snabbdom hande data and aria ? 

Cant we simply use the following fix ?
```js
const considerDataAria = (data) => fn.mapObject(data,
  ([mod, data]) => 
    mod === 'data' ? { dataset: data } :
    mod === 'aria' ? fn.flatifyKeys({ [mod]: data }) :
    { [mod]: data }
)
```

**Comment by jvanbruegge** [comment]
That should work too

**Comment by Swizz** [comment]
Npm published : [v2.3.0](https://github.com/Swizz/snabbdom-pragma/releases/tag/2.3.0)

**Pull request merged**
