### PR TITLE
Split only the first dash in deepifyKeys

### LINKED ISSUE #26: Setting a data attribute with more than one dash does not work
Actual example:

```
let calcKey = 'x'
return <a data-calc-key={calcKey}>
```

Will set el.dataset.calc to [Object object] instead of setting  el.dataset.calcKey to 'x'

The reason is that the following params will be passed:

```
{
  data: {
    calc: {
       key: 'x'
    }
  }
}
```

This struct is created by `deepifyKeys`

### PR DESCRIPTION
**Pull request by blikblum**
Fixes #26 

Change `deepifyKeys` to split only the first dash, so is possible to pass properties with dashes to modules when using `MODULE-PROPERTY` attributes.

### CODE REVIEW

**Comment by Swizz** [comment]
Mays I ask you to fix the following errors in the build ? 
https://travis-ci.org/Swizz/snabbdom-pragma/builds/302801868

Ever will you/us need to use a deep object key in a module ?

**Comment by blikblum** [comment]
I fixed the lint warnings but there's a [buble bug](https://github.com/Rich-Harris/buble/issues/51) that leads to an invalid output

**Comment by blikblum** [comment]
> Ever will you/us need to use a deep object key in a module ?

IMO the usage of properties with dash for style and classes are most common than nested objects. The later case can be done with the standard module syntax

**Comment by blikblum** [comment]
To get working, i changed the implementation to create the nested data separately. Also needed to upgrade buble to 0.17.3. The make command works here, all tests (pre and post) passes, although the CI reports an error when checking to file hash

**Comment by Swizz** [comment]
Npm published with [v2.7.0](https://github.com/Swizz/snabbdom-pragma/releases/tag/2.7.0)

**Pull request merged**
