### PR TITLE
added svg attrs conditional

### LINKED ISSUE #1: Does this handle svg automaticly?
As this is my biggest pain point with snabbdom-jsx. If yes, I will switch to this one

### PR DESCRIPTION
**Pull request by jvanbruegge**
I haven't got to test this, but it should resolve #1

### CODE REVIEW

**Comment by Swizz** [comment]
Sorry, I didnt have enough time last days. I will review it within days.

**Comment by jvanbruegge** [comment]
Any update on this?

**Comment by jvanbruegge** [comment]
I tested this PR locally and everything works now as expected

**Comment by jvanbruegge** [comment]
I released a fixed version under `snabbdom-pragma-quickfix` because I needed a working version on npm

**Comment by Swizz** [comment]
I will take the time to review all your PR right now.

Thanks for the support. And I apologize to be so lazy on it.

**Comment by jvanbruegge** [comment]
I added another fix, the `className` is readonly on svg elements, so you have to use attributes there

**Comment by jvanbruegge** [comment]
I've tested the new fix too, it is working as expected

**Comment by Swizz** [comment]
I have one linting issue to complete.
Then, I will write some tests for the SVG capabilities. And merge your PRs in.

**Comment by jvanbruegge** [comment]
Ok, you should have write access to this PR

**Pull request merged**
